openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8080"
paths:
  /account/login:
    post:
      summary: 登录
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                password:
                  type: string
              required:
                - phone
                - password
            examples:
              '1':
                value:
                  phone: '15603895344'
                  password: _VKUhvtO1arl0Cs
                description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                    required:
                      - token
                required:
                  - code
                  - message
                  - data
              examples:
                '1':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 200
                    message: success
                    data:
                      token: >-
                        eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ3b3JrX3JlY29yZCIsImlzcyI6InN0cmFvc3AuY24iLCJ0b2tlbl9jbGFpbV9waG9uZSI6IjE4MzM5MzU1NzI5IiwidG9rZW5fY2xhaW1fcGFzc3dvcmQiOiIxMjM0NTYiLCJ0b2tlbl9jbGFpbV9hY2NvdW50X2lkIjo0LCJleHAiOjE3NDI5Njg1ODN9.ki36XPa15lkYFeLRt1pTclZAH41hbrU8dfnfrK2PIcg
                '2':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 303
                    message: 用户认证失败，请重新登录
                    data: null
          headers: {}
      security: []
  /account/register:
    post:
      summary: 注册
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                password:
                  type: string
              required:
                - phone
                - password
            examples:
              '1':
                value:
                  phone: '18339355729'
                  password: '123456'
                description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: 'null'
                required:
                  - code
                  - message
                  - data
              examples:
                '1':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 200
                    message: success
                    data:
                      token: >-
                        eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ3b3JrX3JlY29yZCIsImlzcyI6InN0cmFvc3AuY24iLCJ0b2tlbl9jbGFpbV9waG9uZSI6IjE4MzM5MzU1NzI5IiwidG9rZW5fY2xhaW1fcGFzc3dvcmQiOiIxMjM0NTYiLCJ0b2tlbl9jbGFpbV9hY2NvdW50X2lkIjo0LCJleHAiOjE3NDI5NjgzMjV9.NCXpBs3lEAyIIMnlhufZCI6RDN4M5qi47tsCgk5dxJU
                '2':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 302
                    message: 手机号已注册
                    data: null
                '3':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 302
                    message: 手机号已注册
                    data: null
          headers: {}
        x-200-2:
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: 'null'
                required:
                  - code
                  - message
                  - data
          headers: {}
      security: []
  /account/{id}/avatar:
    post:
      summary: 上传头像
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          example: '4'
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  format: binary
                  type: string
                  example: >-
                    file://C:\Users\Strao\Pictures\Screenshots\屏幕截图 2024-12-18
                    110936.png
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: 'null'
                required:
                  - code
                  - message
                  - data
              examples:
                '1':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 200
                    message: Success
                    data: null
          headers: {}
      security:
        - bearer: []
  /account/{id}/password:
    put:
      summary: 更新密码
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          example: '4'
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
              required:
                - oldPassword
                - newPassword
            examples:
              '1':
                value:
                  oldPassword: '1234567'
                  newPassword: '123456'
                description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: 'null'
                required:
                  - code
                  - message
                  - data
              examples:
                '1':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 200
                    message: Success
                    data: null
          headers: {}
      security:
        - bearer: []
  /account/{id}:
    get:
      summary: 根据用户id获取用户信息
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          example: '4'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      header:
                        type: string
                      phone:
                        type: string
                      password:
                        type: string
                      email:
                        type: string
                      sex:
                        type: integer
                      address:
                        type: string
                    required:
                      - id
                      - username
                      - header
                      - phone
                      - password
                      - email
                      - sex
                      - address
                required:
                  - code
                  - message
                  - data
              examples:
                '1':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 200
                    message: success
                    data:
                      id: 4
                      username: '18339355729'
                      header: header_1740563152853_4.png
                      phone: '18339355729'
                      password: '123456'
                      email: ''
                      sex: 0
                      address: ''
          headers: {}
      security:
        - bearer: []
  /workRecord:
    post:
      summary: 添加记录
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                teamSize:
                  type: integer
                singleProductQuantity:
                  type: integer
                singleProductPrice:
                  type: integer
                multipleProductQuantity:
                  type: integer
                multipleProductPrice:
                  type: integer
                workDate:
                  type: string
                  format: date
                  examples:
                    - '2025-03-08'
              required:
                - teamSize
                - singleProductQuantity
                - singleProductPrice
                - multipleProductQuantity
                - multipleProductPrice
                - workDate
            examples:
              '1':
                value:
                  teamSize: 2
                  singleProductQuantity: 10
                  singleProductPrice: 10
                  multipleProductQuantity: 10
                  multipleProductPrice: 10
                  workDate: '2025-03-08'
                description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: 'null'
                required:
                  - code
                  - message
                  - data
              examples:
                '1':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 200
                    message: Success
                    data: null
          headers: {}
      security:
        - bearer: []
  /workRecord/lunar/detail:
    get:
      summary: 获取农历年详细记录
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: year
          in: query
          description: ''
          required: false
          example: '2025'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        teamSize:
                          type: integer
                        singleProductQuantity:
                          type: integer
                        singleProductPrice:
                          type: integer
                        multipleProductQuantity:
                          type: integer
                        multipleProductPrice:
                          type: integer
                        workDate:
                          type: string
                        accountId:
                          type: integer
                      required:
                        - id
                        - teamSize
                        - singleProductQuantity
                        - singleProductPrice
                        - multipleProductQuantity
                        - multipleProductPrice
                        - workDate
                        - accountId
                required:
                  - code
                  - message
                  - data
              examples:
                '1':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 200
                    message: success
                    data:
                      - id: 5
                        teamSize: 2
                        singleProductQuantity: 10
                        singleProductPrice: 10
                        multipleProductQuantity: 10
                        multipleProductPrice: 10
                        workDate: '2025-03-02'
                        accountId: 0
                      - id: 9
                        teamSize: 2
                        singleProductQuantity: 0
                        singleProductPrice: 0
                        multipleProductQuantity: 20
                        multipleProductPrice: 10
                        workDate: '2025-03-07'
                        accountId: 0
                      - id: 12
                        teamSize: 0
                        singleProductQuantity: 10
                        singleProductPrice: 10
                        multipleProductQuantity: 0
                        multipleProductPrice: 0
                        workDate: '2025-03-03'
                        accountId: 0
                      - id: 13
                        teamSize: 0
                        singleProductQuantity: 10
                        singleProductPrice: 10
                        multipleProductQuantity: 0
                        multipleProductPrice: 0
                        workDate: '2025-03-04'
                        accountId: 0
                      - id: 14
                        teamSize: 2
                        singleProductQuantity: 10
                        singleProductPrice: 10
                        multipleProductQuantity: 10
                        multipleProductPrice: 10
                        workDate: '2025-02-27'
                        accountId: 0
          headers: {}
      security:
        - bearer: []
  /workRecord/lunar/summary:
    get:
      summary: 获取农历年总结
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: year
          in: query
          description: ''
          required: false
          example: '2025'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      startWorkDate:
                        type: string
                      endWorkDate:
                        type: string
                      workingDays:
                        type: integer
                      totalSalary:
                        type: integer
                      totalMultipleProductQuantity:
                        type: integer
                      totalSingleProductQuantity:
                        type: integer
                    required:
                      - startWorkDate
                      - endWorkDate
                      - workingDays
                      - totalSalary
                      - totalMultipleProductQuantity
                      - totalSingleProductQuantity
                required:
                  - code
                  - message
                  - data
              examples:
                '1':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 200
                    message: success
                    data:
                      startWorkDate: '2025-01-29'
                      endWorkDate: '2026-02-17'
                      workingDays: 4
                      totalSalary: 450
                      totalMultipleProductQuantity: 30
                      totalSingleProductQuantity: 30
          headers: {}
      security:
        - bearer: []
  /workRecord/month/detail:
    get:
      summary: 获取月份的详细记录
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: year
          in: query
          description: summary / detail
          required: false
          example: '2025'
          schema:
            type: string
        - name: month
          in: query
          description: ''
          required: false
          example: '3'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        teamSize:
                          type: integer
                        singleProductQuantity:
                          type: integer
                        singleProductPrice:
                          type: integer
                        multipleProductQuantity:
                          type: integer
                        multipleProductPrice:
                          type: integer
                        workDate:
                          type: string
                        accountId:
                          type: integer
                      required:
                        - id
                        - teamSize
                        - singleProductQuantity
                        - singleProductPrice
                        - multipleProductQuantity
                        - multipleProductPrice
                        - workDate
                        - accountId
                required:
                  - code
                  - message
                  - data
              examples:
                '1':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 200
                    message: success
                    data:
                      - id: 5
                        teamSize: 2
                        singleProductQuantity: 10
                        singleProductPrice: 10
                        multipleProductQuantity: 10
                        multipleProductPrice: 10
                        workDate: '2025-03-02'
                        accountId: 0
                      - id: 9
                        teamSize: 2
                        singleProductQuantity: 0
                        singleProductPrice: 0
                        multipleProductQuantity: 20
                        multipleProductPrice: 10
                        workDate: '2025-03-07'
                        accountId: 0
                      - id: 12
                        teamSize: 0
                        singleProductQuantity: 10
                        singleProductPrice: 10
                        multipleProductQuantity: 0
                        multipleProductPrice: 0
                        workDate: '2025-03-03'
                        accountId: 0
                      - id: 13
                        teamSize: 0
                        singleProductQuantity: 10
                        singleProductPrice: 10
                        multipleProductQuantity: 0
                        multipleProductPrice: 0
                        workDate: '2025-03-04'
                        accountId: 0
          headers: {}
      security:
        - bearer: []
  /workRecord/month/summary:
    get:
      summary: 获取月份的总结
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: year
          in: query
          description: summary / detail
          required: false
          example: '2025'
          schema:
            type: string
        - name: month
          in: query
          description: ''
          required: false
          example: '3'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      workDate:
                        type: string
                      workingDays:
                        type: integer
                      totalSalary:
                        type: integer
                      totalMultipleProductQuantity:
                        type: integer
                      totalSingleProductQuantity:
                        type: integer
                    required:
                      - workDate
                      - workingDays
                      - totalSalary
                      - totalMultipleProductQuantity
                      - totalSingleProductQuantity
                required:
                  - code
                  - message
                  - data
              examples:
                '1':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 200
                    message: success
                    data:
                      - id: 5
                        teamSize: 2
                        singleProductQuantity: 10
                        singleProductPrice: 10
                        multipleProductQuantity: 10
                        multipleProductPrice: 10
                        workDate: '2025-03-02'
                        accountId: 0
                      - id: 9
                        teamSize: 2
                        singleProductQuantity: 0
                        singleProductPrice: 0
                        multipleProductQuantity: 20
                        multipleProductPrice: 10
                        workDate: '2025-03-07'
                        accountId: 0
                      - id: 12
                        teamSize: 0
                        singleProductQuantity: 10
                        singleProductPrice: 10
                        multipleProductQuantity: 0
                        multipleProductPrice: 0
                        workDate: '2025-03-03'
                        accountId: 0
                      - id: 13
                        teamSize: 0
                        singleProductQuantity: 10
                        singleProductPrice: 10
                        multipleProductQuantity: 0
                        multipleProductPrice: 0
                        workDate: '2025-03-04'
                        accountId: 0
          headers: {}
      security:
        - bearer: []
  /workRecord/{id}:
    put:
      summary: 更新记录
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          example: '14'
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                teamSize:
                  type: integer
                singleProductQuantity:
                  type: integer
                singleProductPrice:
                  type: integer
                multipleProductQuantity:
                  type: integer
                multipleProductPrice:
                  type: integer
                workDate:
                  type: string
              required:
                - teamSize
                - singleProductQuantity
                - singleProductPrice
                - multipleProductQuantity
                - multipleProductPrice
                - workDate
            examples:
              '1':
                value:
                  teamSize: 0
                  singleProductQuantity: 10
                  singleProductPrice: 10
                  multipleProductQuantity: 0
                  multipleProductPrice: 0
                  workDate: '2025-02-27'
                description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: 'null'
                required:
                  - code
                  - message
                  - data
              examples:
                '1':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 200
                    message: success
                    data: null
          headers: {}
      security:
        - bearer: []
    delete:
      summary: 删除记录
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          example: '14'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: 'null'
                required:
                  - code
                  - message
                  - data
              examples:
                '1':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 200
                    message: Success
                    data: null
          headers: {}
      security:
        - bearer: []
    get:
      summary: 根据WorkRecordId查询工作记录
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          example: '12'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      teamSize:
                        type: integer
                      singleProductQuantity:
                        type: integer
                      singleProductPrice:
                        type: integer
                      multipleProductQuantity:
                        type: integer
                      multipleProductPrice:
                        type: integer
                      workDate:
                        type: string
                      accountId:
                        type: integer
                    required:
                      - id
                      - teamSize
                      - singleProductQuantity
                      - singleProductPrice
                      - multipleProductQuantity
                      - multipleProductPrice
                      - workDate
                      - accountId
                required:
                  - code
                  - message
                  - data
              examples:
                '1':
                  summary: 成功示例
                  description: ''
                  value:
                    code: 200
                    message: success
                    data:
                      id: 12
                      teamSize: 0
                      singleProductQuantity: 10
                      singleProductPrice: 10
                      multipleProductQuantity: 0
                      multipleProductPrice: 0
                      workDate: '2025-03-03'
                      accountId: 0
          headers: {}
      security:
        - bearer: []
components:
  schemas:
    Login:
      type: object
      properties:
        phone:
          type: string
        password:
          type: string
      required:
        - phone
        - password
    UpdatePassword:
      type: object
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
      required:
        - oldPassword
        - newPassword
    Token:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    AddWorkRecord:
      type: object
      properties:
        teamSize:
          type: integer
        singleProductQuantity:
          type: integer
        singleProductPrice:
          type: integer
        multipleProductQuantity:
          type: integer
        multipleProductPrice:
          type: integer
        workDate:
          type: string
          format: date
          examples:
            - '2025-03-08'
      required:
        - teamSize
        - singleProductQuantity
        - singleProductPrice
        - multipleProductQuantity
        - multipleProductPrice
        - workDate
    WorkRecord:
      type: object
      properties:
        id:
          type: integer
        teamSize:
          type: integer
        singleProductQuantity:
          type: integer
        singleProductPrice:
          type: integer
        multipleProductQuantity:
          type: integer
        multipleProductPrice:
          type: integer
        workDate:
          type: string
        accountId:
          type: integer
      required:
        - id
        - teamSize
        - singleProductQuantity
        - singleProductPrice
        - multipleProductQuantity
        - multipleProductPrice
        - workDate
        - accountId
    MonthWorkSummary:
      type: object
      properties:
        workDate:
          type: string
        workingDays:
          type: integer
        totalSalary:
          type: integer
        totalMultipleProductQuantity:
          type: integer
        totalSingleProductQuantity:
          type: integer
      required:
        - workDate
        - workingDays
        - totalSalary
        - totalMultipleProductQuantity
        - totalSingleProductQuantity
    YearWorkSummary:
      type: object
      properties:
        startWorkDate:
          type: string
        endWorkDate:
          type: string
        workingDays:
          type: integer
        totalSalary:
          type: integer
        totalMultipleProductQuantity:
          type: integer
        totalSingleProductQuantity:
          type: integer
      required:
        - startWorkDate
        - endWorkDate
        - workingDays
        - totalSalary
        - totalMultipleProductQuantity
        - totalSingleProductQuantity
    UpdateWorkRecord:
      type: object
      properties:
        teamSize:
          type: integer
        singleProductQuantity:
          type: integer
        singleProductPrice:
          type: integer
        multipleProductQuantity:
          type: integer
        multipleProductPrice:
          type: integer
        workDate:
          type: string
      required:
        - teamSize
        - singleProductQuantity
        - singleProductPrice
        - multipleProductQuantity
        - multipleProductPrice
        - workDate
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
